spring.application.name=ocr-project

spring.datasource.url=jdbc:mysql://localhost:3306/ocr_project
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update

tesseract.datapath=D:/Projects/ocr-project/src/main/resources/tessdata
tesseract.language=eng

downloads.directory=D:/Projects/ocr-project/src/main/resources/downloads
